package token

type Type string

const (
	EOF     = "EOF"
	ILLEGAL = "illegal"

	NUM   = "number"
	STR   = "string"
	CHAR  = "char"
	ID    = "identifier"
	PARAM = "parameter"

	PLUS    = "plus"
	MINUS   = "minus"
	STAR    = "star"
	EXP     = "exponent"
	SLASH   = "slash"
	F_DIV   = "floor-div"
	MOD     = "modulo"
	BSLASH  = "backslash"
	LPAREN  = "lparen"
	RPAREN  = "rparen"
	LT      = "less-than"
	GT      = "greater-than"
	LTE     = "less-than-or-equal"
	GTE     = "greater-than-or-equal"
	LBRACE  = "left-brace"
	RBRACE  = "right-brace"
	LSQUARE = "left-square"
	RSQUARE = "right-square"
	SEMI    = "semi"
	EQ      = "equal"
	N_EQ    = "not-equal"
	OR      = "or"
	AND     = "and"
	B_OR    = "bitwise-or"
	B_AND   = "bitwise-and"
	ASSIGN  = "assign"
	DECLARE = "declare"
	COMMA   = "comma"
	ARROW   = "arrow"
	COLON   = "colon"
	Q_MARK  = "question-mark"
	DOT     = "dot"
	F_ARROW = "fat-arrow"
	BANG    = "bang"
	D_COLON = "double-colon"

	A_PLUS   = "assign-plus"
	A_MINUS  = "assign-minus"
	A_STAR   = "assign-star"
	A_EXP    = "assign-exponent"
	A_SLASH  = "assign-slash"
	A_F_DIV  = "assign-floor-div"
	A_MOD    = "assign-modulo"
	A_OR     = "assign-or"
	A_AND    = "assign-and"
	A_B_OR   = "assign-bitwise-or"
	A_B_AND  = "assign-bitwise-and"
	A_Q_MARK = "assign-question-mark"

	DEF     = "def"
	RETURN  = "return"
	TRUE    = "true"
	FALSE   = "false"
	NULL    = "null"
	IF      = "if"
	ELSE    = "else"
	ELIF    = "elif"
	WHILE   = "while"
	FOR     = "for"
	NEXT    = "next"
	BREAK   = "break"
	CLASS   = "class"
	EXTENDS = "extends"
	INIT    = "init"
	MATCH   = "match"
	TRY     = "try"
	CATCH   = "catch"
	IMPORT  = "import"
	USE     = "use"
)
